### ISSUE TITLE
Oracle datasource for CakePHP 3.x

### ISSUE THREAD

**Issue by kasmonaut** [snelg/cakephp-3-oracle#1]
Hi, I was not able to find other means to contact you.

I am very interested in Oracle driver for CakePHP3. Will you continue to develop it to add full functionality? Would you be able to share expected release timelines?
I can offer to help you, although I am not an expert in PHP. I do know Oracle DB failrly well.

Thank you

**Comment by snelg** [comment]
@kasmonaut It's fine to communicate this way, so anyone else who might want to know about this can see the conversation.

So far I have only created as much of this code as is necessary for my job. Most of my development work is with MySQL databases, but I have a few Oracle legacy databases that I sometimes need to use.
I have a few CakePHP 2 projects that use those Oracle databases more extensively. For those projects I used someone else's Cake Oracle driver.
I only have one CakePHP 3 project right now, though, and it only needs to read a few pieces of data from Oracle. So that is all I've implemented so far.

I will definitely continue add features that _I_ need :)
Beyond that, I cannot make any guarantees. But I do have a tiny bit of spare time I could use to try adding some functionality that I don't personally need.

**Comment by kasmonaut** [comment]
Thank you for the update.
Our situation is a bit different. We are on the corporate Oracle DB, trying to embrace CakePHP 3.  I will try to continue to develop insert/update functionality, although a little stack right now, unable to insert data. 
Your help will be greatly appreciated. 
thanks

**Comment by kasmonaut** [comment]
Hi, I have few minor updates  you may be interested in. 
1 Handling more data types - OracleSchema.php
2 Initialization of connection 
I have already merged it with your latest 1.0.1. I can post the code here or would you like another method? email?

**Comment by snelg** [comment]
Best way to do it would be a pull request, as explained here:
https://help.github.com/articles/using-pull-requests/

But I can do it however you'd like.

**Comment by wfgomes** [comment]
Hi guys. I would like to use cakephp 3 in my job and here we use Oracle Database, so I would like to help you guys to continue this project.

**Comment by kasmonaut** [comment]
Hello, guys. I am not actively working on the driver now. The work will resume in few months.
Latest version is what is available here. It can READ, UPDATE and partially INSERT records, but has errors with UPDATE and INSERT. Errors related to sequence of execution form CakePHP

**Comment by wfgomes** [comment]
Hi, I am using it in a little project in my job.  I use just READ and UPDATE.  I have seen the problem with UPDATE, but I set debug false and it works hahaha. I am trying to solve this problem with the sequence of execution.

**Comment by mbhd90** [comment]
Hi all,
I am building a cakePHP 3.0 application and i want to implement Oracle database connection and i have install the plugin through composer. But when i try to bake all components, the system throws an Exception "Exception: Cannot describe s_i18_n. It has 0 columns. in [/var/www/html/3.0/app-master/vendor/cakephp/cakephp/src/Database/Schema/Collection.php, line 98]".
May be i dont have the correct version of CakePHP.
If possible that someone share an empty project cakePHP 3 included Oracle datasource that may help.

**Comment by mbhd90** [comment]
Here the Stack trace of the Exception

Stack Trace:
#0 /var/www/html/3.0/app-master/vendor/cakephp/cakephp/src/Database/Schema/CachedCollection.php(64): Cake\Database\Schema\Collection->describe('s_i18_n', Array)
#1 /var/www/html/3.0/app-master/vendor/cakephp/cakephp/src/ORM/Table.php(423): Cake\Database\Schema\CachedCollection->describe('s_i18_n')
#2 /var/www/html/3.0/app-master/vendor/cakephp/cakephp/src/ORM/Table.php(499): Cake\ORM\Table->schema()
#3 /var/www/html/3.0/app-master/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(194): Cake\ORM\Table->primaryKey()
#4 /var/www/html/3.0/app-master/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(110): Bake\Shell\Task\ModelTask->getAssociations(Object(Cake\ORM\Table))
#5 /var/www/html/3.0/app-master/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(96): Bake\Shell\Task\ModelTask->bake('SI18N')
#6 /var/www/html/3.0/app-master/vendor/cakephp/bake/src/Shell/BakeShell.php(250): Bake\Shell\Task\ModelTask->main('SI18N')
#7 /var/www/html/3.0/app-master/vendor/cakephp/cakephp/src/Collection/CollectionTrait.php(51): Bake\Shell\BakeShell->Bake\Shell{closure}('SI18N', 0)
#8 /var/www/html/3.0/app-master/vendor/cakephp/bake/src/Shell/BakeShell.php(253): Cake\Collection\Collection->each(Object(Closure))
#9 [internal function]: Bake\Shell\BakeShell->all('SI18N')
#10 /var/www/html/3.0/app-master/vendor/cakephp/cakephp/src/Console/Shell.php(443): call_user_func_array(Array, Array)
#11 /var/www/html/3.0/app-master/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(212): Cake\Console\Shell->runCommand(Array, true, Array)
#12 /var/www/html/3.0/app-master/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(179): Cake\Console\ShellDispatcher->_dispatch(Array)
#13 /var/www/html/3.0/app-master/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(126): Cake\Console\ShellDispatcher->dispatch(Array)
#14 /var/www/html/3.0/app-master/bin/cake.php(33): Cake\Console\ShellDispatcher::run(Array)
#15 {main}

**Comment by snelg** [comment]
Pretty sure the individual issues mentioned in this thread have all been resolved.
