### ISSUE TITLE
Erro to connect, PDODriverTrait and Oracle

### ISSUE THREAD

**Issue by adrianodemoura** [snelg/cakephp-3-oracle#18]
Strict (2048): Cake\Database\Driver and Cake\Database\Driver\PDODriverTrait define the same property ($_connection) in the composition of Cake\Oracle\Driver\Oracle. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed [ROOT\vendor\snelg\cakephp-3-oracle\src\Driver\Oracle.php, line 237]
Code Context
Cake\Core\BasePlugin::{closure}() - ROOT\vendor\cakephp\debug_kit\config\bootstrap.php, line 42
include - ROOT\vendor\snelg\cakephp-3-oracle\src\Driver\Oracle.php, line 237
Composer\Autoload\includeFile - ROOT\vendor\composer\ClassLoader.php, line 444
Composer\Autoload\ClassLoader::loadClass() - ROOT\vendor\composer\ClassLoader.php, line 322
spl_autoload_call - [internal], line ??
class_exists - [internal], line ??
Cake\Database\Connection::setDriver() - CORE\src\Database\Connection.php, line 172
Cake\Database\Connection::__construct() - CORE\src\Database\Connection.php, line 119
Cake\Datasource\ConnectionRegistry::_create() - CORE\src\Datasource\ConnectionRegistry.php, line 88
Cake\Core\ObjectRegistry::load() - CORE\src\Core\ObjectRegistry.php, line 96
Cake\Datasource\ConnectionManager::get() - CORE\src\Datasource\ConnectionManager.php, line 204
DebugKit\Panel\SqlLogPanel::initialize() - ROOT\vendor\cakephp\debug_kit\src\Panel\SqlLogPanel.php, line 50
DebugKit\ToolbarService::initializePanels() - ROOT\vendor\cakephp\debug_kit\src\ToolbarService.php, line 196
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 97

**Comment by adrianodemoura** [comment]
i'm using cakephp 3.8.6

**Comment by snelg** [comment]
Fixed. Release 1.2.0.

**Comment by adrianodemoura** [comment]
works fine. thanks.
