### ISSUE TITLE
error in getConnection, setConnection, getValues

### ISSUE THREAD

**Issue by adrianodemoura** [snelg/cakephp-3-oracle#19]
i'm using cake 3.8.6 and driver 1.2.0 i have this erros:

Deprecated Error: ValuesExpression::values() is deprecated. Use ValuesExpression::setValues()/getValues() instead. - ROOT\vendor\snelg\                                                                                                                         cakephp-3-oracle\src\Dialect\OracleDialectTrait.php, line: 61

**Comment by snelg** [comment]
More deprecations fixed. Version 1.2.1
