### ISSUE TITLE
Driver could not be found

### ISSUE THREAD

**Issue by mklappen** [snelg/cakephp-3-oracle#4]
Hi,
Not sure where else to post/ask about this but I have project that has Oracle backend.

In setting up I have
1. enabled the php_oci extensions (running wamp for my dev/localhost)
2. installed cakephp-3-oracle via composer - install appears to have gone through w/o any errors as code was installed into vendor directory and I have a plugin->loadAll() call in my bootstrap.php
3. updated Datasources in app.php to my oracle connection info

When I try to load the root page to see if it's connecting all that is returned is "Database driver Cake\Database\Driver\Oracle could not be found."

Anyone else have similar issues or know if I could have missed a step in installing? 
Thank you

**Comment by snelg** [comment]
"driver" value in Datasources in app.php should be
Cake\ **Oracle** \Driver\Oracle, not
Cake\ **Database** \Driver\Oracle, e.g.

``` php
    'Datasources' => [
        'default' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Oracle\Driver\Oracle',
```

**Comment by mklappen** [comment]
Thank you for quick reply! Ahh... That was the issue. Should have compared more closely with your datasource in the doc.  Of course I simply copied the MySQL entry which is \Database.

On to troubleshooting my next error :)
thanks again.
