### ISSUE TITLE
ORA-00972: identifier is too long

### ISSUE THREAD

**Issue by kasmonaut** [snelg/cakephp-3-oracle#8]
Just run into infamous Oracle ORA-00972: identifier is too long issue.
CakePHP forms queries with convention select tableName.field_name as "tableName__field_name" which generates ORA-00972 error in 11g database. Did not test 12c yet.

**Comment by snelg** [comment]
Annoying, isn't it?
One immediate workaround solution is to alias the tablename. Here's what I have in some of my actual code, including the comments:

``` php
class ControlDatesTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);
        //Oracle has 30-character limit on column names, even "AS blahblah"
        //alias column names. The "CONTROL_DATES" table has some long-ish column
        //names, so when Cake aliases them as "CONTROL_DATES__BLAHBLAHBLAH"
        //they end up a little more than 30 characters. Trimming the default
        //Cake alias fixes that
        $this->alias('Dates');
    }
}
```

That won't quite work if your field names are already too close to 30 characters, though.

A full, proper solution would involve overriding both the "aliasField" function in Cake\Datasource\QueryTrait and the "_calculateColumnMap" function in Cake\ORM\ResultSet.
I haven't figured out the proper, clean way to do that inside a nice, tidy package.

**Comment by kasmonaut** [comment]
Thanks for the reply. I confirmed with our DB admins and Oracle 12c will
still have 30char limit on identifiers.
I played around with "aliasField" function in Cake\ORM\Query. did not find
"aliasField" function in Cake\Datasource\QueryTrait.  I agree, a clean
solution is not trivial, but having "table_name_field_name" convention will
be very limiting. I identify many instances of this problem in our current
project which is very small.

The only idea I have now is to use first initials of table_name  ex:
"CONTROL_DATES"
=> "CD"

**Comment by snelg** [comment]
The code itself is a little ugly, but I wrote a workaround for this problem.
Try the latest release (1.0.11) and let me know if it works for you.

**Comment by kasmonaut** [comment]
Yes, the work around is working. The SQL in the debug window is still
readable, so i do not see to big issues.
Looking at the debug console, I see 37 XXAUTO_SHORTENED fields and this is
a very small project. The 30 char limit is just silly for any modern
application.

Thank you  very much for your help

**Comment by snelg** [comment]
I still think 30 characters is at least somewhat reasonable for an individual table name or field name, but yeah, not being able to have arbitrarily long "AS" aliases is annoying.
